name: .NET

on:
  push:
    branches: [ master, unobot-modules ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Publish
      run: dotnet publish -c Release
    - name: Upload UNObot executable
      uses: actions/upload-artifact@v2
      with:
        name: unobot
        path: src/UNObot/bin/Release/net5.0/win-x64/publish/UNObot.exe
    - name: Upload plugins
      uses: actions/upload-artifact@v2
      with:
        name: unobot-plugins
        path: src/UNObot/bin/Release/net5.0/win-x64/publish/plugins/*.dll
    - name: Upload debug files
      uses: actions/upload-artifact@v2
      with:
        name: unobot-debug
        path: src/UNObot/bin/Release/net5.0/win-x64/publish/**/*.pdb
